### ISSUE TITLE
출시 후 에러가 발생합니다.

### ISSUE THREAD

**Issue by cholnh** [bootpay/flutter#4]
개발환경에서는 BootpayApi가 잘 동작합니다...만
구글 플레이스토어에 **내부 테스트/비공개 트랙**으로 출시 후 실행 해보니,  BootpayApi가 동작하지 않습니다.

출시 된 어플리케이션에서 BootpayApi 코드가 실행되면, 앱 전체가 다운됩니다.

로그캣에 `Application id is not configured.` 라는 에러문구가 써있는데,  
프로젝트 내 코드에는 발급받은 androidApplicationId를 정확하게 입력한 상태입니다.

아래 소스코드와 기기 로그캣입니다.

**request.dart**
```
Payload payload = Payload();
payload.androidApplicationId = '$발급받은_안드로이드_어플리케이션_아이디';

(...)  

await BootpayApi.request(
    context,
    payload,
    (...)
);
```  

  
**logcat**
```
07-19 15:13:46.035 26140-26140/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mrporter.flutter.client.pomangam, PID: 26140
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mrporter.flutter.client.pomangam/kr.co.bootpay.bootpay_api.BootpayActivity}: java.lang.RuntimeException: Application id is not configured.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
        at android.app.ActivityThread.access$900(ActivityThread.java:177)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
     Caused by: java.lang.RuntimeException: Application id is not configured.
        at kr.co.bootpay.b.i()
        at kr.co.bootpay.b.e()
        at kr.co.bootpay.b.a()
        at kr.co.bootpay.bootpay_api.BootpayActivity.a()
        at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate()
        at android.app.Activity.performCreate(Activity.java:6289)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2655)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767) 
        at android.app.ActivityThread.access$900(ActivityThread.java:177) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:5951) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```

**Comment by ehowlsla** [comment]
원인은 정확하게 모르겠으나, 해당에러는 Bootpay Swift에서 valdation check 과정에서 발생시키는 에러입니다.
dart에서 refelction으로 호출하는 과정에서, 예기치않은 에러가 발생하는듯하니, ios_application_id 도 지정 후 재실행해주시고,
문제가 반복된다면 다시 살펴보겠습니다.

**Comment by cholnh** [comment]
바쁘신 와중에도 빠른 응대 감사드립니다.

생략 되었지만 `payload.iosApplicationId` 이 부분 또한 코드에 삽입되어있습니다.
또한 발급 된 ID에 오타가 없는지 확인하였습니다.

**Comment by ehowlsla** [comment]
다시 확인해보니 안드로이드의 validCheck() 기능에서 뱉는 에러는 맞네요.
정확한 안내를 위해 영업일에 부트페이 홈페이지 우측하단 채팅을 통해 문의남겨주세요!

**Comment by ehowlsla** [comment]
버전 1.1.0 으로 다시 테스트해주시면 감사하겠습니다

**Comment by ehowlsla** [comment]
1.1.12 로 다시 테스트해주시면 감사하겠습니다.

**Comment by cholnh** [comment]
1.1.12 테스트 결과 이전과 같은 오류 발생합니다.

개발환경에서는 첫 번째 오류만 발생하고 잘 작동합니다.
출시환경에서는 첫 번째, 두 번째 오류 발생 후 앱이 강제 종료됩니다.

**첫 번째 오류**
```
org.json.JSONException: No value for boot_key
org.json.JSONException: No value for quotas
```
위 오류는 #6 에서 언급된 오류와 같습니다.

**두 번째 오류**
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mrporter.flutter.client.pomangam/kr.co.bootpay.bootpay_api.BootpayActivity}:
 java.lang.RuntimeException: Application id is not configured.
```
해당 오류는 스토어 출시에만 해당 됩니다.

**Comment by cholnh** [comment]
1.1.14 테스트 시 동일 오류 발생합니다.
확인 부탁드립니다.

**Comment by ehowlsla** [comment]
배포가 아니라, 테스트 시 발생하는 에러인가요?
저희가 제공하는 예제 또한 런타임시 문제가 되나요?

**Comment by cholnh** [comment]
안드로이드 플레이스토어에 배포하면 에러 발생합니다.
개발단에서는 문제되지 않습니다.
에러 발생은 폐사 프로젝트 뿐만 아니라, 부트페이에서 제공하는 예제 또한 배포/런타임시 문제가 됩니다.

**Comment by ehowlsla** [comment]
저희가 구글플레이 스토어 출시 후 결제테스트 하였으나, 동일한 현상은 재현되지 않습니다.

**Comment by cholnh** [comment]
app: build.bradle 내에 위치한
`buildTypes` 부분의
`signingConfig signingConfigs.debug` 부분만 제외하고
나머지는 홈페이지에 나와있는 예제 프로젝트랑 동일합니다.
저희는 `signingConfigs` 을 `realse`로 서명 하였습니다.

혹시 이 부분도 문제가 되나요?

**Comment by ehowlsla** [comment]
저도 release 로 서명하였습니다.
fabric 등으로 런타임 오류를 다시 공유해주시면 살펴보도록 하겠습니다.

**Comment by cholnh** [comment]
Firebase Crashlytics 런타임 오류 결과입니다.

Crashlytics (이미지)
![1](https://user-images.githubusercontent.com/23611497/92380370-0e682d80-f144-11ea-9649-52721fd2afc4.jpg)
![2](https://user-images.githubusercontent.com/23611497/92380381-12944b00-f144-11ea-9b7f-8fc2c4da364d.jpg)

Crashlytics (텍스트)
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pomangam.flutter.client.readymeal_client_flutter/kr.co.bootpay.bootpay_api.BootpayActivity}: java.lang.RuntimeException: Application id is not configured.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

```
Caused by java.lang.RuntimeException: Application id is not configured.
       at kr.co.bootpay.b.i(:2)
       at kr.co.bootpay.b.e(:136)
       at kr.co.bootpay.b.a(:4)
       at kr.co.bootpay.bootpay_api.BootpayActivity.a(:146)
       at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate(:98)
       at android.app.Activity.performCreate(Activity.java:7326)
       at android.app.Activity.performCreate(Activity.java:7317)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by ehowlsla** [comment]
주신 정보로 어떤 문제인지 감이 잡히지가 않습니다.
에러로그로만 보면 payload데이터에 값이 없거나, 파싱 후 데이터 바인딩이 올바르지 않다는 의미있지만
맥락상 그런 버그는 아닌듯합니다.

개발단에서 문제되지 않으며, 구글플레이 출시시 문제가 된다면,
혹시 apk 추출, 설치 진행시 문제가 되지 않는지도 확인이 필요할 듯 합니다.
저희측에서는 구글플레이 출시 후 결제테스트 시 동일한 현상은 재현되지 않았습니다.

이 이슈와 관련하여 다른 정보가 있다면 언제든 공유부탁드립니다.

**Comment by ehowlsla** [comment]
주신 정보로 어떤 문제인지 감이 잡히지가 않습니다.
에러로그로만 보면 payload데이터에 값이 없거나, 파싱 후 데이터 바인딩이 올바르지 않다는 의미있지만
맥락상 그런 버그는 아닌듯합니다.

개발단에서 문제되지 않으며, 구글플레이 출시시 문제가 된다면,
혹시 apk 추출, 설치 진행시 문제가 되지 않는지도 확인이 필요할 듯 합니다.
저희측에서는 구글플레이 출시 후 결제테스트 시 동일한 현상은 재현되지 않았습니다.

이 이슈와 관련하여 다른 정보가 있다면 언제든 공유부탁드립니다.

**Comment by cholnh** [comment]
proguard 난독화 과정에서 gson과 bootpay 패키지 rule을 추가하지 않아 발생하는 에러로 확인하였습니다.

`kr.co.bootpay.bootpay_api.BootpayActivity` 에서 `JSON Parser`로 파싱하는 부분을 다시 `Gson`으로 변경 후,
아래와 같은 proguard 룰을 추가 하니 릴리즈 버전에서 잘 동작하였습니다.

**proguard-rules.pro**
``` 
-keepattributes Signature
-keepattributes *Annotation*
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.examples.android.model.** { <fields>; }

-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

-keep class kr.co.bootpay.** { *; }
``` 

**BootpayActivity.java**
``` 
public class BootpayActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);

        { ... }

        Gson gson = new Gson();
        Payload payload = gson.fromJson(payloadString, Payload.class);
        if(userString != null && !userString.isEmpty()) 
            bootUser = gson.fromJson(userString, BootUser.class);
        if(itemsString != null && !itemsString.isEmpty()) 
            items =  gson.fromJson(itemsString, new TypeToken<List<Item>>(){}.getType());
        if(extraString != null && !extraString.isEmpty()) 
            bootExtra =  gson.fromJson(extraString, BootExtra.class);

        goBootpayRequest(payload, bootUser, bootExtra, items);
    }
}
``` 

다음 업데이트때  `JSON Parser`로 파싱하는 부분을 다시 `Gson`으로 되돌려주시면 감사하겠습니다.
이유는, 기존 코드에서 `JSONObject` 변환 후 내부 변환 결과를 얻어오는 `getString`, `getBoolean` 등의 로직에서 
`JSONObject`의 Null 유무를 판별하지 않아 오류가 발생하고 있었습니다.
```
String ux = object.getString("sms_use");    //  org.json.JSONException: No value for sms_use
```

**Comment by ehowlsla** [comment]
1.2.21 버전에서 관련 이슈는 모두 해결되었습니다.
