### ISSUE TITLE
Application id is not configured 에러

### ISSUE THREAD

**Issue by jpung0629** [bootpay/flutter#5]
디버그 모드에서 예제 코드 따라서 테스트 중인데 
Application id is not configured 에러가 발생합니다.

**개발 환경입니다.**
```
flutter doctor -v

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.3 19D76, locale ko-KR)
    • Flutter version 1.17.4 at /Users/pungjunghyeon/dev/flutter
    • Framework revision 1ad9baa8b9 (5 weeks ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/pungjunghyeon/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • Android SDK built for x86             • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPad Pro (12.9-inch) (4th generation) • DD19A125-0B75-48B9-B541-F78C6D579986 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

No issues found!
```
**테스트 코드입니다.**
```
  goBootpayRequest(BuildContext context) async {
    Payload payload = Payload();
    payload.androidApplicationId = '[안드로이드 어플리케이션 id]';
    payload.iosApplicationId = '[ios 어플리케이션 id]';
    payload.pg = 'payapp';
    payload.methods = ['phone', 'card'];
    payload.name = 'test';
    payload.price = 2000;
    payload.orderId = DateTime.now().millisecondsSinceEpoch.toString();

    User user = User();
    user.username = 'test';
    user.email = 'email';
    user.area = 'area';
    user.addr = 'dkdk';
    user.phone = 'phone';

    Extra extra = Extra();
    extra.appScheme = 'bootpayFlutterSample';

    Item item = Item();
    item.itemName = '테스트 방';
    item.qty = 1;
    item.unique = DateTime.now().millisecondsSinceEpoch.toString();
    item.price = 2000;

    BootpayApi.request(
      context,
      payload,
      extra: extra,
      user: user,
      items: [item],
      onDone: (String json){
        debugPrint('onDone: $json');
      },
      onError:  (String json) {
        debugPrint('onDone: $json');
      },
      onCancel: (String json) {
        debugPrint('onDone: $json');
      },
      onReady: (String json) {
        debugPrint('onDone: $json');
      }
    );
  }
```
**에러 내용입니다.**
```
W/ActivityThread(27651): handleWindowVisibility: no activity for token android.os.BinderProxy@399452e
W/llyo.billyo_ap(27651): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (greylist, reflection, allowed)
W/llyo.billyo_ap(27651): Accessing hidden method Lsun/misc/Unsafe;->allocateInstance(Ljava/lang/Class;)Ljava/lang/Object; (greylist, reflection, allowed)
D/AndroidRuntime(27651): Shutting down VM
E/AndroidRuntime(27651): FATAL EXCEPTION: main
E/AndroidRuntime(27651): Process: com.billyo.billyo_app, PID: 27651
**E/AndroidRuntime(27651): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.billyo.billyo_app/kr.co.bootpay.bootpay_api.BootpayActivity}: java.lang.RuntimeException: Application id is not configured.**
E/AndroidRuntime(27651): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
E/AndroidRuntime(27651): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
E/AndroidRuntime(27651): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(27651): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27651): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27651): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(27651): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27651): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27651): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(27651): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27651): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(27651): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(27651): Caused by: java.lang.RuntimeException: Application id is not configured.
E/AndroidRuntime(27651): 	at kr.co.bootpay.b.i(:596)
E/AndroidRuntime(27651): 	at kr.co.bootpay.b.e(:436)
E/AndroidRuntime(27651): 	at kr.co.bootpay.b.a(:480)
E/AndroidRuntime(27651): 	at kr.co.bootpay.bootpay_api.BootpayActivity.a(:106)
E/AndroidRuntime(27651): 	at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate(:46)
E/AndroidRuntime(27651): 	at android.app.Activity.performCreate(Activity.java:7802)
E/AndroidRuntime(27651): 	at android.app.Activity.performCreate(Activity.java:7791)
E/AndroidRuntime(27651): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E/AndroidRuntime(27651): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
E/AndroidRuntime(27651): 	... 11 more 

```

**Comment by ehowlsla** [comment]
올바른 application id 를 넣어주세요

**Comment by jpung0629** [comment]
application id는 부트페이 관리자 페이지에서 가져온 값이 들어간 상태입니다.
안드로이드, IOS 각각 다르게 줬습니다.

**Comment by ehowlsla** [comment]
부트페이 홈페이지 우측하단 버튼을 통해 채팅으로 문의주시면 감사하겠습니다

**Comment by ehowlsla** [comment]
1.1.12 로 다시 테스트해주시면 감사하겠습니다.
