### ISSUE TITLE
안드로이드 스튜디오에서 적용 시 아래와 같은 오류가 발생합니다

### ISSUE THREAD

**Issue by Acver14** [bootpay/flutter#6]
아래와 같은 에러가 발생한 후 어플이 종료됩니다. 도움 주시면 감사하겠습니다.

W/ActivityThread(27722): handleWindowVisibility: no activity for token android.os.BinderProxy@769a11e
W/System.err(27722): org.json.JSONException: No value for boot_key
W/System.err(27722): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(27722): 	at org.json.JSONObject.getString(JSONObject.java:560)
W/System.err(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.getPayload(BootpayActivity.java:76)
W/System.err(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate(BootpayActivity.java:50)
W/System.err(27722): 	at android.app.Activity.performCreate(Activity.java:7802)
W/System.err(27722): 	at android.app.Activity.performCreate(Activity.java:7791)
W/System.err(27722): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
W/System.err(27722): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
W/System.err(27722): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
W/System.err(27722): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
W/System.err(27722): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(27722): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(27722): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
W/System.err(27722): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(27722): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(27722): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(27722): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(27722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/System.err(27722): org.json.JSONException: No value for quotas
W/System.err(27722): 	at org.json.JSONObject.get(JSONObject.java:399)
W/System.err(27722): 	at org.json.JSONObject.getJSONArray(JSONObject.java:594)
W/System.err(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.getBootExtra(BootpayActivity.java:178)
W/System.err(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate(BootpayActivity.java:53)
W/System.err(27722): 	at android.app.Activity.performCreate(Activity.java:7802)
W/System.err(27722): 	at android.app.Activity.performCreate(Activity.java:7791)
W/System.err(27722): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
W/System.err(27722): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
W/System.err(27722): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
W/System.err(27722): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
W/System.err(27722): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err(27722): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err(27722): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
W/System.err(27722): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/System.err(27722): 	at android.os.Looper.loop(Looper.java:214)
W/System.err(27722): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(27722): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(27722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(27722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/AndroidRuntime(27722): Shutting down VM
E/AndroidRuntime(27722): FATAL EXCEPTION: main
E/AndroidRuntime(27722): Process: com.example.ssdam, PID: 27722
E/AndroidRuntime(27722): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ssdam/kr.co.bootpay.bootpay_api.BootpayActivity}: java.lang.IllegalStateException: undefined is not classified
E/AndroidRuntime(27722): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
E/AndroidRuntime(27722): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
E/AndroidRuntime(27722): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/AndroidRuntime(27722): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(27722): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(27722): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(27722): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(27722): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27722): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(27722): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(27722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(27722): Caused by: java.lang.IllegalStateException: undefined is not classified
E/AndroidRuntime(27722): 	at kr.co.bootpay.valid.PGAvailable.stringToPG(PGAvailable.java:90)
E/AndroidRuntime(27722): 	at kr.co.bootpay.valid.PGAvailable.getDefaultMethods(PGAvailable.java:47)
E/AndroidRuntime(27722): 	at kr.co.bootpay.valid.ValidRequest.validPGDialog(ValidRequest.java:31)
E/AndroidRuntime(27722): 	at kr.co.bootpay.valid.ValidRequest.validUXAvailablePG(ValidRequest.java:20)
E/AndroidRuntime(27722): 	at kr.co.bootpay.BootpayBuilder.request(BootpayBuilder.java:483)
E/AndroidRuntime(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.goBootpayRequest(BootpayActivity.java:293)
E/AndroidRuntime(27722): 	at kr.co.bootpay.bootpay_api.BootpayActivity.onCreate(BootpayActivity.java:55)
E/AndroidRuntime(27722): 	at android.app.Activity.performCreate(Activity.java:7802)
E/AndroidRuntime(27722): 	at android.app.Activity.performCreate(Activity.java:7791)
E/AndroidRuntime(27722): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E/AndroidRuntime(27722): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
E/AndroidRuntime(27722): 	... 11 more
I/Process (27722): Sending signal. PID: 27722 SIG: 9
Lost connection to device.

**Comment by ehowlsla** [comment]
영업일에 홈페이지 우측 하단 채팅을 통해 문의주시기 바랍니다

**Comment by ehowlsla** [comment]
1.1.13 으로 사용해주시면 감사하겠습니다

**Comment by ehowlsla** [comment]
1.2.21 버전에서 관련 이슈는 모두 해결되었습니다.
